cookie:
  expiry_days: 30
  key: woshizhongruiheyindeliurui
  name: chinassic_auth_cookie
credentials:
  usernames:
    '15908130915':
      email: tanwk@chinassic.com
      first_name: weikang
      last_name: tan
      password: zrty600030
      roles:
      - viewer

    hezijie:
      email: henryovo62@gmail.com
      first_name: zijie
      last_name: he
      password: a12345679
      roles:
      - admin
pre-authorized:
  emails:
  - henryovo62@gmail.com
  - tanwk@chinassic.com
